package com.trollema.appdata.constants;

/**
 * MajorData: contains the static data of all the college majors supported by the applicaiton
 * Created by Jinming Yu
 */
public class MajorData {
    public static String[] validMajor = {
            "architecture",
            "organic farming",
            "urban farming",
            "applied health",
            "athletic training",
            "biology",
            "chemistry",
            "environmental science",
            "exercise kinesiology",
            "exercise science",
            "fisheries and wildlife",
            "food science",
            "forest management",
            "marine science",
            "nursing",
            "pharmacy",
            "pre - dental",
            "pre - medical",
            "pre - veterinary medicine",
            "apparel design",
            "textile design",
            "dance",
            "film",
            "broadcast",
            "fine art",
            "studio art",
            "graphic design",
            "interior design",
            "industrial design",
            "landscape architecture",
            "music",
            "theatre",
            "urban planning",
            "video game design",
            "web design",
            "digital media",
            "arts management",
            "education",
            "english", "writing",
            "equine science",
            "history",
            "non-profit management",
            "journalism",
            "language studies",
            "peace studies",
            "conflict studies",
            "philosophy",
            "political science",
            "social science",
            "gender studies",
            "human service mgmt.",
            "aerospace engineering",
            "astronomy",
            "biomedical engineering",
            "chemical engineering",
            "computer science",
            "civil engineering",
            "electrical engineering",
            "energy science",
            "engineering",
            "industrial engineering",
            "imaging science",
            "materials science",
            "mathematics",
            "mechanical engineering",
            "environmental engineering",
            "applied science",
            "aviation",
            "aeronautics",
            "business",
            "finance",
            "construction management",
            "emergency management",
            "family science",
            "consumer science",
            "hospitality management",
            "public health",
            "recreation&tourism mgmt",
            "sport management",
            "sports turf/golf mgmt",
            "forensic science",
            "entertainment mgmt",
            "military science/rotc",
            "computational media",
            "nuclear and radiological engineering",
            "international affairs",
            "history, technology, and society",
            "economics",
            "applied mathematics",
            "applied physics",
            "biochemistry",
            "discrete mathematics",
            "psychology"
    };
}
